### Products create

POST http://localhost:3000/products
# Non-dynamic: Just run the POST request
Content-type: application/json

{
  "name": "Harness",
  "price": 40,
  "image_url": "placeholder",
  "description": "A harness"
}