### Products index

GET http://localhost:3000/products

### Products show

GET http://localhost:3000/products/1

### Products create

POST http://localhost:3000/products
# Non-dynamic: Just run the POST request
Content-type: application/json

{
  "name": "Harness",
  "price": 40,
  "image_url": "placeholder",
  "description": "A harness"
}

### Products update
PATCH http://localhost:3000/products/3
Content-type: application/json

{
  "name": "Hiking Shoes",
  "price": 89
}