### Products index

GET http://localhost:3000/products.json

### Products show

GET http://localhost:3000/products/3.json

### Products create

POST http://localhost:3000/products.json
# Non-dynamic: Just run the POST request
Content-type: application/json

{
  "name": "To be destroyed",
  "price": 0,
  "image_url": "placeholder",
  "description": "To be destroyed"
}

### Products update
PATCH http://localhost:3000/products/3.json
Content-type: application/json

{
  "name": "Hiking Shoes",
  "price": 89
}

### Products destroy
DELETE http://localhost:3000/products/9.json