### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}