@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI5MDcxNzF9.vmIlqdzCii49Xrj7ProM91MIw4PdkUSM-EWuNnj0HgA
@contentType = application/json

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### ORDERS SHOW
GET http://localhost:3000/orders/3.json
Authorization: Bearer {{jwt}}

### ORDER CREATE
POST http://localhost:3000/orders.json 
Content-Type: {{contentType}}
Authorization: Bearer {{jwt}}

{
  "product_id": 3,
  "quantity": 2
}