@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMwNjg0NDZ9.1O1cPQ-1Kfef8m4N4rVKV_6QLi_E97e69VR6v9rfyus
@contentType = application/json

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### ORDERS SHOW
GET http://localhost:3000/orders/3.json
Authorization: Bearer {{jwt}}

### ORDER CREATE
POST http://localhost:3000/orders.json 
Authorization: Bearer {{jwt}}
