@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTQ4MDAyOTN9.xCLfVgjVoy3G2QkvI9CpIwNpyGZ4kFDA7Bo55vzqFuM

### Products index

GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}


### Products show

GET http://localhost:3000/products/3.json

### Products create

POST http://localhost:3000/products.json
# Non-dynamic: Just run the POST request
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "To be destroyed",
  "price": 40,
  "image_url": "placeholder",
  "description": "To be destroyed",
  "supplier_id": 1
}

### Products update
PATCH http://localhost:3000/products/4.json
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Hiking Shoes",
  "price": 69.99
}

### Products destroy
DELETE http://localhost:3000/products/4.json
Authorization: Bearer {{jwt}}